---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - ci-semaphore-configmap.yaml
  - eventbus.yaml
  - eventsource.yaml
  - ingressroute.yaml
  - workflow-templates/common.yaml
  - workflow-templates/terraform.yaml
  - workflow-templates/docker-build.yaml
  - workflow-templates/ansible.yaml
  - workflow-templates/image-build.yaml
  - sensors/terraform-authentik.yaml
  - sensors/terraform-datadog.yaml
  - sensors/terraform-digitalocean.yaml
  - sensors/terraform-tailscale.yaml
  - sensors/terraform-tfe.yaml
  - sensors/build-memory-webhook.yaml
  - sensors/build-ci-terraform.yaml
  - sensors/build-ci-ansible.yaml
  - sensors/terraform-vault.yaml
  - sensors/ansible-inlet.yaml
  - sensors/ansible-k3s.yaml
