---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - eventbus.yaml
  - eventsource.yaml
  - ingressroute.yaml
  - workflow-templates/common.yaml
  - workflow-templates/terraform.yaml
  - workflow-templates/docker-build.yaml
  - sensors/terraform-authentik.yaml
  - sensors/terraform-datadog.yaml
  - sensors/terraform-digitalocean.yaml
  - sensors/terraform-tailscale.yaml
  - sensors/terraform-tfe.yaml
  - sensors/build-memory-webhook.yaml
