# ---------------------------------------------------------------------------
# ATS Website — OIDC provider (Auth.js manages the session, not Authentik)
# ---------------------------------------------------------------------------

# Scope mappings — only needed for OIDC providers (not used by proxy apps above)
data "authentik_property_mapping_provider_scope" "openid" {
  scope_name = "openid"
}

data "authentik_property_mapping_provider_scope" "email" {
  scope_name = "email"
}

data "authentik_property_mapping_provider_scope" "profile" {
  scope_name = "profile"
}

resource "authentik_provider_oauth2" "ats_website" {
  name               = "ATS Website"
  authorization_flow = data.authentik_flow.default_authorization.id
  invalidation_flow  = data.authentik_flow.default_invalidation.id

  client_id = "ats-website"
  # client_secret is auto-generated by Authentik; Terraform captures it in state
  # and writes it to Vault below — no manual step required.

  redirect_uris = ["https://ats.${local.base_domain}/api/auth/callback/authentik"]

  property_mappings = [
    data.authentik_property_mapping_provider_scope.openid.id,
    data.authentik_property_mapping_provider_scope.email.id,
    data.authentik_property_mapping_provider_scope.profile.id,
  ]

  access_token_validity = local.app_token_validity

  lifecycle {
    ignore_changes = [jwt_federation_providers, jwt_federation_sources]
  }
}

resource "authentik_application" "ats_website" {
  name               = "ATS Website"
  slug               = "ats-website"
  protocol_provider  = authentik_provider_oauth2.ats_website.id
  meta_launch_url    = "https://ats.${local.base_domain}"
  meta_description   = "Furry Association Website"
  policy_engine_mode = "any"
  open_in_new_tab    = true
}

# Write the generated OIDC credentials to a dedicated Vault path.
# Kept separate from secret/ats-website (which holds DATABASE_URL, AUTH_SECRET, etc.)
# so Terraform owns exactly the keys it generates and nothing else.
resource "vault_kv_secret_v2" "ats_website_authentik" {
  mount = "secret"
  name  = "authentik/ats-website"

  data_json = jsonencode({
    AUTHENTIK_CLIENT_ID     = authentik_provider_oauth2.ats_website.client_id
    AUTHENTIK_CLIENT_SECRET = authentik_provider_oauth2.ats_website.client_secret
    AUTHENTIK_ISSUER        = "https://authentik.${local.base_domain}/application/o/ats-website/"
  })
}
