---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ats-postgres
  namespace: prod-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: ats-postgres
