---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jellyseerr
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: jellyseerr
            chart: jellyseerr
            chartVersion: 14.0.1
            namespace: prod-media
            manifestPath: argocd/applications/media/jellyseerr

  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default

      sources:
        - repoURL: oci.trueforge.org/truecharts
          chart: "{{chart}}"
          targetRevision: "{{chartVersion}}"
          helm:
            values: |
              operator:
                verify:
                  enabled: false
                traefik:
                  namespace: prod-infra
              ingress:
                main:
                  integrations:
                    traefik:
                      enableFixedMiddlewares: false
                      middlewares:
                  enabled: true
                  hosts:
                    - host: jellyseerr.st0rmingbr4in.com
                      paths:
                        - path: /
              resources:
                limits:
                  memory: 500Mi
                requests:
                  cpu: 500m
                  memory: 500Mi
              workload:
                main:
                  podSpec:
                    containers:
                      main:
                        probes:
                          liveness:
                            enabled: true
                            type: exec
                            command:
                              - sh
                              - -c
                              - touch /config/.liveness
                            spec:
                              initialDelaySeconds: 12
                              periodSeconds: 15
                              failureThreshold: 5
                              timeoutSeconds: 5
                          readiness:
                            enabled: true
                            type: http
                            path: /
                            spec:
                              initialDelaySeconds: 15
                              periodSeconds: 10
              persistence:
                config:
                  enabled: true
                  existingClaim: jellyseerr-config
        - repoURL: https://github.com/St0rmingBr4in/home-kube-flux-config
          targetRevision: HEAD
          path: "{{manifestPath}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      ignoreDifferences:
        - group: "*"
          kind: "Secret"
          jsonPointers:
            - /data
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/template/spec/hostUsers
