---
operator:
  verify:
    enabled: false
  traefik:
    namespace: prod-infra

ingress:
  main:
    integrations:
      traefik:
        enableFixedMiddlewares: false
        middlewares:
    enabled: true
    hosts:
      - host: jellyseerr.st0rmingbr4in.com
        paths:
          - path: /

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - sh
                - -c
                - touch /config/.liveness
              spec:
                initialDelaySeconds: 12
                periodSeconds: 15
                failureThreshold: 5
                timeoutSeconds: 5
            readiness:
              enabled: true
              type: http
              path: /
              spec:
                initialDelaySeconds: 15
                periodSeconds: 10

persistence:
  config:
    enabled: true
    existingClaim: jellyseerr-config
