---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ci-build-ci-terraform
  namespace: argo
spec:
  template:
    serviceAccountName: argo-ci
  dependencies:
    - name: push
      eventSourceName: github
      eventName: push
      filters:
        data:
          - path: body.ref
            type: string
            value:
              - "refs/heads/master"
  triggers:
    - template:
        name: trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-build-ci-terraform-
                namespace: argo
              spec:
                workflowTemplateRef:
                  name: ci-image-build
                arguments:
                  parameters:
                    - name: git-ref
                      value: "refs/heads/master"
                    - name: git-sha
                      value: ""
                    - name: path-filter
                      value: "ci/images/ci-terraform"
                    - name: image
                      value: "docker.io/st0rmingbr4in/ci-terraform"
                    - name: context
                      value: "ci/images/ci-terraform"
          parameters:
            - src:
                dependencyName: push
                dataKey: body.ref
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: push
                dataKey: body.after
              dest: spec.arguments.parameters.1.value
      retryStrategy:
        steps: 3
