---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pihole
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: pihole
            chart: pihole
            chartVersion: 2.35.0
            namespace: prod-infra
            repoURL: https://mojo2600.github.io/pihole-kubernetes/

  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
    spec:
      project: default

      sources:
        - repoURL: "{{repoURL}}"
          chart: "{{chart}}"
          targetRevision: "{{chartVersion}}"
          helm:
            values: |
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
              serviceDns:
                type: LoadBalancer
                loadBalancerClass: tailscale
                annotations:
                  tailscale.com/hostname: "pihole"
                  tailscale.com/proxy-class: "proxy-resources"
              serviceWeb:
                type: ClusterIP
              doh:
                enabled: false
              persistentVolumeClaim:
                enabled: false
              DNS1: "1.1.1.1"
              DNS2: "1.0.0.1"
              dnsmasq:
                upstreamServers: []
                customDnsEntries: []
              admin:
                enabled: true
              livenessProbe:
                httpGet:
                  path: /admin/
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 15
                failureThreshold: 5
              readinessProbe:
                httpGet:
                  path: /admin/
                  port: http
                initialDelaySeconds: 15
                periodSeconds: 10
                failureThreshold: 3
              monitoring:
                podMonitor:
                  enabled: false

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
