---
operator:
  verify:
    enabled: false
  traefik:
    namespace: prod-infra

# Disable built-in ingress to use custom IngressRoute
ingress:
  main:
    enabled: false

securityContext:
  runAsUser: 1025

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 512Mi

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - sh
                - -c
                - touch /config/.liveness
              spec:
                initialDelaySeconds: 12
                periodSeconds: 15
                failureThreshold: 5
                timeoutSeconds: 5
            readiness:
              enabled: true
              type: http
              path: /
              spec:
                initialDelaySeconds: 15
                periodSeconds: 10

persistence:
  config:
    enabled: true
    existingClaim: bazarr-config
  media:
    enabled: true
    existingClaim: media-library
    mountPath: /tv
