---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-credentials
spec:
  type: kv-v2
  mount: secret
  path: app-health-hooks/argocd
  destination:
    name: argocd-credentials
    create: true
  refreshAfter: 24h
  vaultAuthRef: prod-infra/default
