---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Application Categories
  - infrastructure/
  - core/
  - media/
  - compliance/memory-webhook/applicationset.yaml
  - external-services/external-service-prod-infra/applicationset.yaml
  - ci/
