---
- name: Configure WAN masquerade NAT
  community.network.edgeos_config:
    lines:
      - set service nat rule 5010 description "masquerade for WAN"
      - set service nat rule 5010 log disable
      - set service nat rule 5010 outbound-interface eth5.832
      - set service nat rule 5010 protocol all
      - set service nat rule 5010 type masquerade
    save: true
