---
operator:
  verify:
    enabled: false
  traefik:
    namespace: prod-infra

ingress:
  main:
    enabled: false

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

exportarrResources:
  limits:
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

securityContext:
  runAsUser: 1031
  runAsGroup: 100

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - sh
                - -c
                - touch /config/.liveness
              spec:
                initialDelaySeconds: 12
                periodSeconds: 15
                failureThreshold: 5
                timeoutSeconds: 5
            readiness:
              enabled: true
              type: http
              path: /
              spec:
                initialDelaySeconds: 15
                periodSeconds: 10

persistence:
  config:
    enabled: true
    existingClaim: radarr-config
  media:
    enabled: true
    existingClaim: media-library
    subPath: Movies
    mountPath: /movies
  downloads:
    enabled: true
    existingClaim: media-downloads
    mountPath: /downloads
