name: Terraform - Authentik

on:
  push:
    branches: [master]
    paths:
      - terraform/authentik/**
      - .github/workflows/terraform-authentik.yml
  pull_request:
    paths:
      - terraform/authentik/**
      - .github/workflows/terraform-authentik.yml

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/authentik

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - uses: hashicorp/setup-terraform@b9cd54531c595c04d4ec14f7e8b6d7f28fd9822 # v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -parallelism=1
        env:
          TF_VAR_authentik_token: ${{ secrets.AUTHENTIK_TOKEN }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -parallelism=1
        env:
          TF_VAR_authentik_token: ${{ secrets.AUTHENTIK_TOKEN }}
