name: Terraform - Tailscale

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - terraform/tailscale/**
      - .github/workflows/terraform-tailscale.yml
  pull_request:
    paths:
      - terraform/tailscale/**
      - .github/workflows/terraform-tailscale.yml

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

      - name: Terraform Lint
        run: make lint-terraform

      - name: Terraform Init
        run: make terraform-tailscale-init

      - name: Terraform Plan
        run: make terraform-tailscale-plan
        env:
          TF_VAR_tailscale_oauth_client_id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          TF_VAR_tailscale_oauth_client_secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: make terraform-tailscale-apply
        env:
          TF_VAR_tailscale_oauth_client_id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          TF_VAR_tailscale_oauth_client_secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}

      - name: Report to Datadog CI Visibility
        if: always()
        run: make ci-report
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
